package org.example;

public enum State {
    START,
    GET_CONTACT,
    GET_LOCATION,
    CABINET, CATEGORY_LIST, SHOW_CATEGORY, SHOW_PRODUCT, PRODUCT_LIST, PRODUCT_SELECTED, COUNTING, SHOW_CATEGORIES, CHOOSE_CATEGORY,

}
